### ISSUE TITLE
navigate to next change?

### ISSUE THREAD

**Issue by mmcnl** [pgsandstrom/vscode-navigate-edit-history#10]
Hello and thanks for this nifty plugin!

I was wondering if you'd consider adding a command to navigate to the next (more recent) change. This would allow going back and forth through the stack like is possible in `vim`, eg see here with the `g;` and `g,` commands:
https://vim.fandom.com/wiki/List_changes_to_the_current_file#Using_a_change_list

**Comment by pgsandstrom** [comment]
Hi and thank you :) This sounds like a good feature, I'll add it when I get some time. Most likely in a week or two. I'd also accept a PR.

**Comment by mmcnl** [comment]
Thank you @pgsandstrom ! 🎉

**Comment by pgsandstrom** [comment]
You're welcome! Let me know if you spot any bugs. :)
