### ISSUE TITLE
moveCursorToNextEditInCurrentFile?

### ISSUE THREAD

**Issue by maxwellhibbert** [pgsandstrom/vscode-navigate-edit-history#13]
Hi, I'm really enjoying this extension, I'm just in need of an extra command that's confusingly missing: moveCursorToNextEditInCurrentFile. I can go back, but not forwards in the current file...

**Comment by pgsandstrom** [comment]
Hi! Glad to hear that you found the extension useful :)

This looks like an oversight on my part, and a quick fix. So I just released an upgrade that adresses this.

Thanks for the feedback! Let me know if you detect any bugs in the new version.

**Comment by maxwellhibbert** [comment]
Awesome! you rock 👍
Moving back and forth in the current file only is super handy for me.
