### ISSUE TITLE
Cursor is one character behind

### ISSUE THREAD

**Issue by nikhilvijayanv** [pgsandstrom/vscode-navigate-edit-history#15]
When navigating to a change where characters where inserted the cursor is positioned just before the last entered character. 

![edit-history](https://user-images.githubusercontent.com/64440/150648461-f4f531c4-86d1-4c02-a0dc-b69cd2135869.gif)

**Comment by pgsandstrom** [comment]
Thank you for the bug report! I just released version 1.6.0 that should adress this. Please let me know if you run into any issues.
