### ISSUE TITLE
A dedicated shortcut/command for current file only

### ISSUE THREAD

**Issue by certainlyakey** [pgsandstrom/vscode-navigate-edit-history#2]
Thanks for a great plugin! 

I'm wondering, is it possible to add a command to only go to previous edit in the current file?

**Comment by pgsandstrom** [comment]
Hi! Absolutely. I'll make sure to add it to the next version.

May I ask how you found this plugin? I thought it would be to niche to be used outside my circle of friends.

**Comment by certainlyakey** [comment]
Hi! Thanks a lot :) 
I found it via [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=codeandstuff.vscode-navigate-edit-history).

**Comment by pgsandstrom** [comment]
I just published a new version. I didn't pick a default keybinding for the command, but you can add one yourself. Thanks for the feedback! :)
