### ISSUE TITLE
Cursor disappears (focus is lost) when navigating between files

### ISSUE THREAD

**Issue by russelldavis** [pgsandstrom/vscode-navigate-edit-history#24]
When using the `moveCursorToPreviousEdit` command (via keyboard shortcut), if it navigages to a different file, the cursor disappears (focus is lost from the document). I tracked this down to the `preserveFocus: true` option being passed to `showTextDocument` (PR forthcoming).

**Comment by pgsandstrom** [comment]
Awesome job! This is what makes me love open source :)

I just released a new version with your fix. Let me know if you run into any more problems!
