### ISSUE TITLE
Idea: Improve discover-ability by changing title displayed on vscode marketplace

### ISSUE THREAD

**Issue by javalight** [pgsandstrom/vscode-navigate-edit-history#6]
### Current title: Vscode Navigate Edit History

If we look at some common search terms like: [bookmarks](https://marketplace.visualstudio.com/search?term=bookmarks&target=VSCode&category=All%20categories&sortBy=Relevance), [jump](https://marketplace.visualstudio.com/search?term=jump&target=VSCode&category=All%20categories&sortBy=Relevance), [edits](https://marketplace.visualstudio.com/search?term=edits&target=VSCode&category=All%20categories&sortBy=Relevance). The extension does not appear.

Might make sense to adjust the title for better discover-ability. 

### New title: Edits History Bookmarks

This should get the search terms: edits, edit, bookmarks, bookmark, marks, mark, history. == Large audience.   

Or other titles might be:
- Jump Edits History with Bookmarks

**Comment by pgsandstrom** [comment]
Good point. I think "Edit History Bookmarks" is a good title. I'll soon get around to changing it. I'll add some keywords to the description as well.
