### ISSUE TITLE
Feature Request. Would be great if you could add an option to search files in show all edit menu.

### ISSUE THREAD

**Issue by Lee182** [pgsandstrom/vscode-navigate-edit-history#7]
Hi thankyou for the extension a real time saver.

It would be great if you could make an option to search file paths as well as edits. Edits though with show with first priority. Then file path matches.

**Comment by pgsandstrom** [comment]
That sounds like a cool feature. But currently I'm quite busy, so it might take some time until I get around to implementing it. You are welcome to submit a PR if you want.

**Comment by Lee182** [comment]
PR up if you want to look.  It was pretty easy didn't know it was a built in vscode option.
